### ISSUE TITLE
Typo in repo name

### ISSUE THREAD

**Issue by SevereOverfl0w** [Ivana-/bb-degug#2]
Should it be debug? not de-G-ug?

**Comment by Ivana-** [comment]
Yes, you are right, this was a simply typo mistake. But now I do not know how to change a repo name/address and is it possible al all.

**Comment by SevereOverfl0w** [comment]
https://help.github.com/en/articles/renaming-a-repository

**Comment by Ivana-** [comment]
Thanks alot! I just was not sure if any related pages will redirected to the new name, but your link explains it. Done.
